import Head from 'next/head'
import styles from '../styles/pages/Home.module.css'
import Earth from "../components/earth";
import {Canvas} from "@react-three/fiber";

const Home = () => {
    return (
        <>
            <Head>
                <title>Chad Cotton</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="icon.png"/>
            </Head>
            <main className={styles.main}>
                <Canvas shadows={true} camera={{position: [8, 2, 0]}}>
                    <Earth/>
                </Canvas>
            </main>
        </>
    )
}

export default Home
